import { pgTable, serial, varchar, integer, boolean, timestamp, date, text, jsonb, uniqueIndex } from "drizzle-orm/pg-core";

export const students = pgTable("students", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  rateCents: integer("rate_cents").notNull(), // D-07: integer cents, never float
  parentEmail: varchar("parent_email", { length: 255 }).notNull(), // D-13: required
  zoomLink: varchar("zoom_link", { length: 512 }), // ZOOM-01: optional per-student Zoom link; nullable
  archived: boolean("archived").notNull().default(false), // D-10/D-11: soft delete
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// invoices must be declared above sessions since sessions.invoiceId
// references it — the `() => invoices.id` thunk would also handle a forward
// reference, but declaring it here keeps the file read top-to-bottom.
export const invoices = pgTable("invoices", {
  id: serial("id").primaryKey(),
  studentId: integer("student_id")
    .notNull()
    .references(() => students.id, { onDelete: "restrict" }), // Pitfall 3: mirrors sessions FK, protects history; D-04: no invoice number column
  periodStart: date("period_start", { mode: "string" }).notNull(), // D-03: frozen min session date
  periodEnd: date("period_end", { mode: "string" }).notNull(), // D-03: frozen max session date
  totalCents: integer("total_cents").notNull(), // frozen sum at generation, integer cents per P2 D-14
  // frozen line items: {date,durationMinutes,amountCents,notes}[] — see lib/invoice/render.ts
  lineItems: jsonb("line_items").notNull(),
  renderedBody: text("rendered_body").notNull(), // Pitfall 4: frozen full body, never re-rendered from live Settings
  renderedSubject: text("rendered_subject").notNull(), // WR-03: text (not varchar 500) — a {student} merge can push a near-500 subject past the old bound and crash the atomic INSERT
  generatedAt: timestamp("generated_at").notNull().defaultNow(),
  autoGenerated: boolean("auto_generated").notNull().default(false), // D-07: true = generated by the cadence cron; existing rows are manual → default false
  sent: boolean("sent").notNull().default(false), // D-08: best-effort local sent flag; NOT a delivery signal. New inserts set this explicitly; existing rows are backfilled to true after push
});

export const settings = pgTable("settings", {
  id: integer("id").primaryKey().default(1), // single-row config, always id=1
  zelleHandle: varchar("zelle_handle", { length: 255 }).notNull().default(""), // SET-01
  subjectTemplate: varchar("subject_template", { length: 500 }).notNull(), // SET-02/D-13
  bodyTemplate: text("body_template").notNull(), // SET-02/D-12
  timezone: varchar("timezone", { length: 64 }), // SET-03: IANA zone captured for Phase 5/6; nullable so the form can prefill the browser-detected zone (D-11/D-12)
  invoiceCadenceEnabled: boolean("invoice_cadence_enabled").notNull().default(false), // RINV-01/D-01: master on/off for auto-invoicing; day is retained while off
  invoiceCadenceDay: integer("invoice_cadence_day"), // RINV-01/D-02: day-of-month 1–28; ignored when invoiceCadenceLastDay is true
  invoiceCadenceLastDay: boolean("invoice_cadence_last_day").notNull().default(false), // D-02: 'last day of month' — avoids ambiguous 29/30/31
  lastInvoicedMonth: varchar("last_invoiced_month", { length: 7 }), // D-03 monthly high-water-mark 'YYYY-MM'; null = never run; guarantees at most once per calendar month
  gmailUserEmail: varchar("gmail_user_email", { length: 255 }), // BULK-01: tutor's Gmail address; nullable until configured
  gmailAppPassword: text("gmail_app_password"), // BULK-01: encrypted ciphertext (format: "iv:encrypted"); nullable until configured
  gmailVerified: boolean("gmail_verified").notNull().default(false), // BULK-05: verification status after test send
  gmailLastError: text("gmail_last_error"), // BULK-05: last verification error message for UI display
  autoSendInvoices: boolean("auto_send_invoices").notNull().default(false), // BULK-AUTO: auto-send invoices after monthly generation (opt-in)
});

// Declared above sessions since sessions.scheduleSlotId references it. Weekly
// recurring class slots per student — the source the daily cron auto-logs from.
export const scheduleSlots = pgTable("schedule_slots", {
  id: serial("id").primaryKey(),
  studentId: integer("student_id")
    .notNull()
    .references(() => students.id, { onDelete: "restrict" }), // mirror sessions — never cascade history
  weekday: integer("weekday").notNull(), // 0=Sun … 6=Sat, getUTCDay convention
  startTime: varchar("start_time", { length: 5 }).notNull(), // "HH:mm" 24h local wall-clock, TZ-naive
  durationMinutes: integer("duration_minutes").notNull(),
  effectiveDate: date("effective_date", { mode: "string" }).notNull(), // D-08: = creation date; auto-log floor, no retroactive backfill
  lastLoggedDate: date("last_logged_date", { mode: "string" }), // D-05 high-water-mark; null = never processed
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const sessions = pgTable("sessions", {
  id: serial("id").primaryKey(),
  studentId: integer("student_id")
    .notNull()
    .references(() => students.id, { onDelete: "restrict" }), // never cascade — archived students keep history
  date: date("date", { mode: "string" }).notNull(), // mode "string": avoids TZ-shift
  durationMinutes: integer("duration_minutes").notNull(), // hours+minutes combine into this
  amountCents: integer("amount_cents").notNull(), // D-14: frozen snapshot, computed server-side once at write time
  notes: text("notes"), // SESS-02: optional
  makeup: boolean("makeup").notNull().default(false), // MK-01: internal-only label for a rescheduled class. Never affects amountCents and never renders on an invoice — see lib/invoice/render.ts
  billed: boolean("billed").notNull().default(false), // Phase 3 sets true; Phase 2 only reads for DASH-02
  invoiceId: integer("invoice_id").references(() => invoices.id, { onDelete: "set null" }), // null = unbilled; set at generation, un-links on invoice delete (D-16)
  scheduleSlotId: integer("schedule_slot_id").references(() => scheduleSlots.id, { onDelete: "set null" }), // D-04: null = manual; set = auto-logged from this slot (drives the D-03 marker). set null: slot delete preserves history (D-06), never cascades
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// DISM-01: a pending occurrence the tutor explicitly discarded (class cancelled,
// student away). Pending occurrences are *derived* from scheduleSlots on every
// request and never stored, so "don't show this one again" needs its own row —
// there is no session record to mark. Keyed by (slotId, date), the same pair
// that identifies an occurrence everywhere else in the calendar code.
// onDelete cascade (not restrict, unlike sessions/invoices): a dismissal is a
// UI preference about a slot, not billing history — deleting the slot makes it
// meaningless, and orphans would silently suppress nothing.
export const dismissedOccurrences = pgTable(
  "dismissed_occurrences",
  {
    id: serial("id").primaryKey(),
    scheduleSlotId: integer("schedule_slot_id")
      .notNull()
      .references(() => scheduleSlots.id, { onDelete: "cascade" }),
    date: date("date", { mode: "string" }).notNull(), // mode "string": avoids TZ-shift, matches sessions.date
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    // Makes "dismiss" idempotent — a double-click or a replayed Server Action
    // can't create two rows for the same occurrence, and restore stays a
    // single unambiguous delete.
    uniqueIndex("dismissed_occurrences_slot_date_idx").on(t.scheduleSlotId, t.date),
  ],
);

export const loginAttempts = pgTable("login_attempts", {
  ipAddress: varchar("ip_address", { length: 45 }).primaryKey(), // IPv6-safe length
  failedCount: integer("failed_count").notNull().default(0),
  lockedUntil: timestamp("locked_until"),
});
