// Monthly invoice cadence engine (RINV-02). On the daily cron, if auto-invoicing
// is on AND today is on/after the cadence day AND this month hasn't already been
// invoiced, generates one invoice per student with unbilled sessions, then records
// the month as invoiced.
//
// Pattern mirrors runAutoLog (Phase 5 D-03): high-water-mark discipline ensures
// at most one run per calendar month, even when the daily cron is late/skipped.
// Per-student try/catch ensures one failure never blocks the rest (D-04).
// The double-billing CTE guard is the safety net if the HWM is ever bypassed.

import { eq } from "drizzle-orm";
import { getDaysInMonth } from "date-fns";

import { db } from "@/lib/db";
import { sessions, settings } from "@/lib/db/schema";
import { generateInvoiceForStudent } from "@/lib/invoice/generate";
import { DEFAULT_TIMEZONE, todayInZone } from "@/lib/schedule/time";

export async function runInvoiceCadence(): Promise<{
  generated: number;
  skipped: number;
  ranThisMonth: boolean;
  invoiceIds: number[];
}> {
  let generated = 0;
  let skipped = 0;
  const invoiceIds: number[] = [];

  // Guard 1: Load settings and check if cadence is enabled.
  const [settingsRow] = await db
    .select()
    .from(settings)
    .where(eq(settings.id, 1));

  if (!settingsRow?.invoiceCadenceEnabled) {
    // Cadence is off — early return.
    return { generated, skipped, ranThisMonth: false, invoiceIds };
  }

  // Guard 2: Resolve timezone and compute today in the user's zone.
  const tz = settingsRow.timezone ?? DEFAULT_TIMEZONE;
  const today = todayInZone(tz);
  const month = today.slice(0, 7); // "YYYY-MM"

  // Guard 3: Check HWM — if we already ran this calendar month, don't run again.
  // This is the key self-heal mechanism: a late/skipped daily run still fires the
  // next day (today.day >= effectiveDay), but the HWM guarantees at most one run
  // per calendar month.
  if (settingsRow.lastInvoicedMonth === month) {
    return { generated, skipped, ranThisMonth: false, invoiceIds };
  }

  // Guard 4: Resolve the effective cadence day.
  // If invoiceCadenceLastDay is true, use the last day of this month.
  // Otherwise, use invoiceCadenceDay (default 1), clamped to the number of days
  // in this month (so day 31 on a 28-day month becomes day 28).
  const daysInMonth = getDaysInMonth(new Date(`${today}T00:00:00`));
  const effectiveDay = settingsRow.invoiceCadenceLastDay
    ? daysInMonth
    : Math.min(settingsRow.invoiceCadenceDay ?? 1, daysInMonth);

  // If today is before the effective cadence day, we're not yet ready to run.
  if (Number(today.slice(8, 10)) < effectiveDay) {
    return { generated, skipped, ranThisMonth: false, invoiceIds };
  }

  // Guard 5: Run the generation loop. Select DISTINCT studentId from sessions
  // where billed = false. For each student, attempt to generate an invoice.
  // Per-student try/catch ensures one failure never blocks the rest.
  const unbilledStudents = await db
    .selectDistinct({ studentId: sessions.studentId })
    .from(sessions)
    .where(eq(sessions.billed, false));

  for (const { studentId } of unbilledStudents) {
    try {
      // Call the shared atomic helper with autoGenerated: true (no throughDate cutoff).
      const result = await generateInvoiceForStudent({
        studentId,
        autoGenerated: true,
      });

      if (result.ok) {
        generated++;
        if (result.invoiceId) {
          invoiceIds.push(result.invoiceId);
        }
      } else {
        skipped++;
      }
    } catch {
      // Caught error — count as skipped and continue.
      skipped++;
    }
  }

  // Guard 6: Advance the HWM. After processing all students (regardless of
  // individual outcomes), mark this month as done so we don't fire again until
  // the next calendar month arrives.
  await db
    .update(settings)
    .set({ lastInvoicedMonth: month })
    .where(eq(settings.id, 1));

  return { generated, skipped, ranThisMonth: true, invoiceIds };
}
