// Invoice generation atomic core — a reusable helper that performs the
// exact double-billing-guarded db.batch CTE that both the manual Server Action
// and the cadence cron call (RINV-02/03). Exported as a pure async function
// (no "use server" — it lives in a plain module imported by both server-only
// and utility files), returns a discriminated GenResult type.

import { and, asc, eq, inArray, sql } from "drizzle-orm";

import { db } from "@/lib/db";
import { sessions, settings, students } from "@/lib/db/schema";
import { formatCents } from "@/lib/format";
import {
  DEFAULT_BODY_TEMPLATE,
  DEFAULT_SUBJECT_TEMPLATE,
} from "@/lib/invoice/defaults";
import {
  buildLineItems,
  formatPeriod,
  renderInvoiceText,
  renderTemplate,
} from "@/lib/invoice/render";

// Discriminated union: GenResult.ok = true carries the email-draft pieces
// and invoice id; ok = false carries the failure reason for error-handling
// mapping (one of four terminal states).
export type GenResult =
  | {
      ok: true;
      invoiceId: number;
      parentEmail: string;
      renderedSubject: string;
      renderedBody: string;
    }
  | {
      ok: false;
      reason: "no-sessions" | "no-student" | "race-lost" | "error";
    };

// Atomically generate an invoice for a single student, reusing the exact
// Phase-3 double-billing-guarded db.batch CTE. Called by both the manual
// Server Action (autoGenerated: false) and the cadence cron (autoGenerated: true).
// Returns a discriminated GenResult — callers pattern-match on ok to determine
// success and error recovery.
export async function generateInvoiceForStudent(opts: {
  studentId: number;
  autoGenerated: boolean;
  throughDate?: string | null;
}): Promise<GenResult> {
  const { studentId, autoGenerated } = opts;
  // Plan 04: throughDate cutoff

  // Re-SELECT unbilled sessions server-side — never trust a client-echoed
  // session-id list or total (Anti-Patterns / T-03-04). Unbilled means
  // billed: false (equivalent to `eq(sessions.billed, false)` below).
  const unbilledSessions = await db
    .select()
    .from(sessions)
    .where(and(eq(sessions.studentId, studentId), eq(sessions.billed, false)))
    .orderBy(asc(sessions.date));

  if (unbilledSessions.length === 0) {
    // Defensive race guard — no unbilled sessions to invoice.
    return { ok: false, reason: "no-sessions" };
  }

  const [student] = await db
    .select()
    .from(students)
    .where(eq(students.id, studentId));

  if (!student) {
    return { ok: false, reason: "no-student" };
  }

  const [settingsRow] = await db
    .select()
    .from(settings)
    .where(eq(settings.id, 1));

  const subjectTemplate =
    settingsRow?.subjectTemplate ?? DEFAULT_SUBJECT_TEMPLATE;
  const bodyTemplate = settingsRow?.bodyTemplate ?? DEFAULT_BODY_TEMPLATE;
  const zelleHandle = settingsRow?.zelleHandle ?? "";

  // P2 D-14: total is the sum of each session's stored amountCents, never
  // re-derived from the student's current rate.
  const totalCents = unbilledSessions.reduce(
    (sum, session) => sum + session.amountCents,
    0,
  );
  const periodStart = unbilledSessions[0].date;
  const periodEnd = unbilledSessions[unbilledSessions.length - 1].date;
  const period = formatPeriod(periodStart, periodEnd);

  const lineItems = buildLineItems(unbilledSessions);
  const invoiceBlock = renderInvoiceText(student.name, period, lineItems);

  const mergeValues = {
    invoice: invoiceBlock,
    student: student.name,
    total: formatCents(totalCents),
    zelle: zelleHandle,
    period,
  };

  // Pitfall 4: freeze the FULLY rendered body + subject now — never
  // re-rendered from a live Settings read later.
  const renderedBody = renderTemplate(bodyTemplate, mergeValues);
  const renderedSubject = renderTemplate(subjectTemplate, mergeValues);

  // T-03-05-01: the invoice INSERT and the sessions mark-billed UPDATE MUST
  // commit as one unit — a crash between two separate writes (or a two-tab
  // race) could otherwise leave sessions un-billed under a persisted
  // invoice, or let the same sessions be billed twice. This is a single
  // data-modifying CTE run via db.execute, wrapped in ONE db.batch call (the
  // interactive transaction() API is NOT used — it throws at runtime on the
  // neon-http driver this project uses). The INSERT is itself gated on all
  // target sessions still being unbilled (double-billing guard): if a
  // concurrent generation already claimed any of them, `ins` inserts zero
  // rows and the trailing UPDATE (gated on `EXISTS (SELECT 1 FROM ins)`)
  // updates zero rows too — no partial commit, no double invoice.
  const sessionIds = unbilledSessions.map((session) => session.id);
  const targetFilter = and(
    inArray(sessions.id, sessionIds),
    eq(sessions.billed, false),
  );

  let newInvoiceId: number | null = null;

  try {
    const [result] = await db.batch([
      db.execute<{ invoice_id: number }>(sql`
        WITH target AS (
          SELECT id FROM sessions WHERE ${targetFilter}
        ),
        ins AS (
          INSERT INTO invoices (
            student_id, period_start, period_end, total_cents,
            line_items, rendered_body, rendered_subject,
            auto_generated, sent
          )
          SELECT ${studentId}, ${periodStart}, ${periodEnd}, ${totalCents},
            ${JSON.stringify(lineItems)}::jsonb, ${renderedBody}, ${renderedSubject},
            ${autoGenerated}, false
          WHERE (SELECT count(*) FROM target) = ${sessionIds.length}
          RETURNING id
        )
        UPDATE sessions
        SET billed = true, invoice_id = (SELECT id FROM ins)
        WHERE ${targetFilter} AND EXISTS (SELECT 1 FROM ins)
        RETURNING (SELECT id FROM ins) AS invoice_id
      `),
    ]);

    newInvoiceId = result.rows[0]?.invoice_id ?? null;
  } catch {
    return { ok: false, reason: "error" };
  }

  if (newInvoiceId === null) {
    // The race was lost: another generation already claimed one or more of
    // these sessions between our re-SELECT above and this write.
    return { ok: false, reason: "race-lost" };
  }

  return {
    ok: true,
    invoiceId: newInvoiceId,
    parentEmail: student.parentEmail,
    renderedSubject,
    renderedBody,
  };
}
