"use client";

import Link from "next/link";
import { format } from "date-fns";
import { useState } from "react";

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button, buttonVariants } from "@/components/ui/button";
import { formatCents } from "@/lib/format";
import { formatPeriod } from "@/lib/invoice/render";
import { cn } from "@/lib/utils";
import { BulkSendConfirmationDialog } from "./bulk-send-confirmation-dialog";
import { sendBulkInvoices } from "@/lib/actions/email";

export interface InvoiceHistoryRow {
  id: number;
  studentName: string | null;
  parentEmail: string | null;
  periodStart: string;
  periodEnd: string;
  totalCents: number;
  renderedSubject: string;
  renderedBody: string;
  generatedAt: Date;
  autoGenerated: boolean;
  sent: boolean;
}

interface InvoiceHistoryTableProps {
  rows: InvoiceHistoryRow[];
  gmailVerified?: boolean;
}

export function InvoiceHistoryTable({ rows, gmailVerified }: InvoiceHistoryTableProps) {
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());
  const [confirmDialogOpen, setConfirmDialogOpen] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [resultMessage, setResultMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);

  const unsentRows = rows.filter((r) => !r.sent);
  const selectedRows = unsentRows.filter((r) => selectedIds.has(r.id));

  const handleSelectToggle = (id: number) => {
    const newSet = new Set(selectedIds);
    if (newSet.has(id)) {
      newSet.delete(id);
    } else {
      newSet.add(id);
    }
    setSelectedIds(newSet);
  };

  const handleSelectAll = () => {
    if (selectedIds.size === unsentRows.length) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(unsentRows.map((r) => r.id)));
    }
  };

  const handleConfirmSend = async () => {
    setIsSending(true);
    setResultMessage(null);

    try {
      const result = await sendBulkInvoices(Array.from(selectedIds));

      if (result.ok) {
        setResultMessage({
          type: "success",
          text: `Sent ${result.sent} invoice${result.sent === 1 ? "" : "s"}${result.failed > 0 ? `, ${result.failed} failed` : ""}`,
        });
        setSelectedIds(new Set());
        setConfirmDialogOpen(false);
        // In a real app, would revalidate the data here
      } else {
        setResultMessage({
          type: "error",
          text: result.error || "Failed to send invoices",
        });
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      setResultMessage({
        type: "error",
        text: message,
      });
    } finally {
      setIsSending(false);
    }
  };

  if (rows.length === 0) {
    return (
      <div className="flex flex-col items-center gap-2 py-16 text-center">
        <h2 className="text-xl leading-tight font-semibold text-zinc-900">
          No invoices yet
        </h2>
        <p className="text-base text-zinc-600">
          Generate your first invoice from the Dashboard to see it here.
        </p>
        <Link
          href="/dashboard"
          className={cn(buttonVariants({ variant: "outline" }), "mt-4")}
        >
          Go to Dashboard
        </Link>
      </div>
    );
  }

  return (
    <>
      {!gmailVerified && (
        <div className="mb-4 rounded-md bg-blue-50 p-3 text-sm text-blue-800">
          Set up email delivery in Settings to send invoices.
        </div>
      )}

      {resultMessage && (
        <div
          className={`mb-4 rounded-md p-3 text-sm ${
            resultMessage.type === "success"
              ? "bg-green-50 text-green-800"
              : "bg-red-50 text-red-800"
          }`}
        >
          {resultMessage.text}
        </div>
      )}

      {selectedIds.size > 0 && (
        <div className="mb-4 flex items-center justify-between rounded-lg border border-zinc-200 bg-white p-3">
          <span className="text-sm text-zinc-600">
            {selectedIds.size} invoice{selectedIds.size === 1 ? "" : "s"} selected
          </span>
          <div className="flex gap-2">
            <Button
              onClick={() => setConfirmDialogOpen(true)}
              disabled={isSending || !gmailVerified}
              className="bg-blue-600 text-white hover:bg-blue-700"
              size="sm"
            >
              Send Selected
            </Button>
            <Button
              onClick={() => setSelectedIds(new Set())}
              variant="outline"
              size="sm"
            >
              Clear Selection
            </Button>
          </div>
        </div>
      )}

      <BulkSendConfirmationDialog
        isOpen={confirmDialogOpen}
        invoices={selectedRows}
        isPending={isSending}
        onConfirm={handleConfirmSend}
        onCancel={() => setConfirmDialogOpen(false)}
      />

      {/* md+ breakpoint: table */}
      <div className="hidden rounded-lg border border-zinc-200 bg-white md:block">
        <Table>
          <TableHeader>
            <TableRow>
              {gmailVerified && (
                <TableHead className="w-12">
                  <input
                    type="checkbox"
                    checked={
                      unsentRows.length > 0 && selectedIds.size === unsentRows.length
                    }
                    onChange={handleSelectAll}
                    className="rounded border-zinc-300"
                  />
                </TableHead>
              )}
              <TableHead>Student</TableHead>
              <TableHead>Period</TableHead>
              <TableHead>Total</TableHead>
              <TableHead>Generated</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map((row) => (
              <TableRow key={row.id}>
                {gmailVerified && !row.sent && (
                  <TableCell>
                    <input
                      type="checkbox"
                      checked={selectedIds.has(row.id)}
                      onChange={() => handleSelectToggle(row.id)}
                      className="rounded border-zinc-300"
                    />
                  </TableCell>
                )}
                {gmailVerified && row.sent && <TableCell />}
                <TableCell className="font-medium text-zinc-900">
                  <div className="flex flex-col gap-1">
                    <div>{row.studentName ?? "Unknown student"}</div>
                    <div className="flex gap-2">
                      {row.autoGenerated && (
                        <span className="rounded bg-zinc-100 px-2 py-0.5 text-xs text-zinc-600">
                          Auto
                        </span>
                      )}
                      {!row.sent && (
                        <span className="rounded bg-amber-100 px-2 py-0.5 text-xs text-amber-800">
                          Not sent yet
                        </span>
                      )}
                      {row.sent && (
                        <span className="rounded bg-green-100 px-2 py-0.5 text-xs text-green-800">
                          Sent
                        </span>
                      )}
                    </div>
                  </div>
                </TableCell>
                <TableCell>
                  {formatPeriod(row.periodStart, row.periodEnd)}
                </TableCell>
                <TableCell>{formatCents(row.totalCents)}</TableCell>
                <TableCell>{format(row.generatedAt, "PPP")}</TableCell>
                <TableCell className="text-right">
                  <div className="flex justify-end gap-2">
                    <Link
                      href={`/history/${row.id}`}
                      className={buttonVariants({
                        variant: "outline",
                        size: "sm",
                      })}
                    >
                      View
                    </Link>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {/* Below md: stacked cards (matches StudentTable/SessionTable) */}
      <div className="flex flex-col gap-3 md:hidden">
        {rows.map((row) => (
          <div
            key={row.id}
            className="flex flex-col gap-2 rounded-lg border border-zinc-200 bg-white p-4"
          >
            <div className="flex items-start justify-between gap-2">
              <div className="flex flex-col gap-1 flex-1">
                <div className="flex items-center gap-2">
                  {gmailVerified && !row.sent && (
                    <input
                      type="checkbox"
                      checked={selectedIds.has(row.id)}
                      onChange={() => handleSelectToggle(row.id)}
                      className="rounded border-zinc-300"
                    />
                  )}
                  <span className="text-base font-medium text-zinc-900">
                    {row.studentName ?? "Unknown student"}
                  </span>
                </div>
                <div className="flex gap-2">
                  {row.autoGenerated && (
                    <span className="rounded bg-zinc-100 px-2 py-0.5 text-xs text-zinc-600">
                      Auto
                    </span>
                  )}
                  {!row.sent && (
                    <span className="rounded bg-amber-100 px-2 py-0.5 text-xs text-amber-800">
                      Not sent yet
                    </span>
                  )}
                  {row.sent && (
                    <span className="rounded bg-green-100 px-2 py-0.5 text-xs text-green-800">
                      Sent
                    </span>
                  )}
                </div>
              </div>
              <Link
                href={`/history/${row.id}`}
                className={buttonVariants({ variant: "outline", size: "sm" })}
              >
                View
              </Link>
            </div>
            <span className="text-base text-zinc-600">
              {formatPeriod(row.periodStart, row.periodEnd)}
            </span>
            <span className="text-base text-zinc-600">
              {formatCents(row.totalCents)}
            </span>
            <span className="text-base text-zinc-600">
              {format(row.generatedAt, "PPP")}
            </span>
          </div>
        ))}
      </div>
    </>
  );
}
