"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { eq } from "drizzle-orm";
import { z } from "zod";

import { db } from "@/lib/db";
import { invoices, sessions } from "@/lib/db/schema";
import {
  generateInvoiceForStudent,
} from "@/lib/invoice/generate";
import { invoiceGenerateSchema } from "@/lib/validation/invoice";

export interface InvoiceActionState {
  fieldErrors: Record<string, string[]> | null;
  invoiceId: number | null;
  // MAIL-05: on success, the raw pieces the CLIENT uses to build the Gmail
  // compose URL and auto-open the draft (the action never builds the URL or
  // sends — sending stays client-side). null on every failure path.
  emailDraft: { to: string; subject: string; body: string } | null;
}

// INV-01..04: generating an invoice totals ALL of a student's unbilled
// sessions, atomically freezes an immutable snapshot, and marks those
// sessions billed. Only `studentId` crosses the client boundary — everything
// else (sessions, student, settings) is re-fetched server-side (T-03-04).
// Delegates the atomic generation to the shared helper (lib/invoice/generate.ts)
// so both the manual path and the cadence cron use the same double-billing-guarded
// CTE (D-04).
export async function generateInvoiceAction(
  _prevState: InvoiceActionState,
  formData: FormData,
): Promise<InvoiceActionState> {
  const parsed = invoiceGenerateSchema.safeParse({
    studentId: formData.get("studentId"),
  });

  if (!parsed.success) {
    return {
      fieldErrors: z.flattenError(parsed.error).fieldErrors,
      invoiceId: null,
      emailDraft: null,
    };
  }

  const { studentId } = parsed.data;

  const result = await generateInvoiceForStudent({
    studentId,
    autoGenerated: false,
  });

  if (!result.ok) {
    // Map each failure reason to the existing fieldErrors strings (no new messages).
    const reasonToFieldError: Record<string, string[]> = {
      "no-sessions": ["This student has no unbilled sessions to invoice."],
      "no-student": ["Select a student."],
      "race-lost": [
        "These sessions were already invoiced in another request. Please refresh and try again.",
      ],
      error: ["Couldn't generate the invoice — please try again."],
    };

    return {
      fieldErrors: { studentId: reasonToFieldError[result.reason] },
      invoiceId: null,
      emailDraft: null,
    };
  }

  revalidatePath("/dashboard");
  revalidatePath("/history");

  return {
    fieldErrors: null,
    invoiceId: result.invoiceId,
    // result.parentEmail is guaranteed present; the client builds the Gmail URL
    // from these frozen pieces and auto-opens the draft.
    emailDraft: {
      to: result.parentEmail,
      subject: result.renderedSubject,
      body: result.renderedBody,
    },
  };
}

// D-16: the only supported mistake-recovery path — deleting an invoice
// atomically un-bills every session it covered (billed: false, invoiceId:
// null) and removes the invoice row, via db.batch (never the interactive
// transaction() API, which throws at runtime on this project's neon-http
// driver — Pitfall 2). Guarded by a positive-integer id check before any DB
// write, mirroring deleteSessionAction.
export async function deleteInvoiceAction(id: number): Promise<void> {
  const invoiceId = Number(id);
  if (!Number.isInteger(invoiceId) || invoiceId <= 0) {
    throw new Error("Invalid invoice id.");
  }

  await db.batch([
    db
      .update(sessions)
      .set({ billed: false, invoiceId: null })
      .where(eq(sessions.invoiceId, invoiceId)),
    db.delete(invoices).where(eq(invoices.id, invoiceId)),
  ]);

  revalidatePath("/dashboard");
  revalidatePath("/history");

  // Server Action throws-to-navigate — no client router plumbing needed;
  // this is why the action returns void, unlike generate which needed to
  // return the new id.
  redirect("/history");
}
